project_identifier_env: CROWDIN_BOTTENDER_PROJECT_ID
api_key_env: CROWDIN_BOTTENDER_API_KEY
base_path: './'
preserve_hierarchy: true

files:
  - source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'ja': 'ja'
        'zh-TW': 'zh-TW'
  - source: '/website/versioned_docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: *anchor
  - source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor
