version: 2
# Reference variables.
references:
  docker_default: &docker_12
    working_directory: /tmp/app
    docker:
      - image: node:12
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"
  docker_default: &docker_10
    working_directory: /tmp/app
    docker:
      - image: node:10
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Taipei"

jobs:
  build-node-10:
    <<: *docker_10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{checksum "yarn.lock"}}
            - node-10-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn --frozen-lockfile
      - run:
          name: build
          command: npm run compile
      - save_cache:
          key: node-10-cache-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/dist
  lint-node-10:
    <<: *docker_10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run lint
          command: npm run lint
  test-node-10:
    <<: *docker_10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: npm run testonly:cov -- --no-cache --colors
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: junit.xml
  build-node-12:
    <<: *docker_12
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-12-cache-{{checksum "yarn.lock"}}
            - node-12-cache
      - run:
          name: install dependencies
          command: |
            yarn config set cache-folder .yarn-cache
            yarn --frozen-lockfile
            yarn add -W codecov
      - run:
          name: build
          command: npm run compile
      - save_cache:
          key: node-12-cache-{{checksum "yarn.lock"}}
          paths:
            - .yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/dist
  lint-node-12:
    <<: *docker_12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run lint
          command: npm run lint
  test-node-12:
    <<: *docker_12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: npm run testonly:cov -- --no-cache --colors && ./node_modules/.bin/codecov
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: junit.xml

workflows:
  version: 2
  test-on-node-versions:
    jobs:
      - build-node-10
      - test-node-10:
          requires:
            - build-node-10
      - build-node-12
      - lint-node-12:
          requires:
            - build-node-12
      - test-node-12:
          requires:
            - build-node-12
