# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    branches:
      - "**"

env:
  CI: true

jobs:
  build:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: yarn --frozen-lockfile

      - name: Compile TypeScript files
        run: npm run compile

      - name: Run lint rules
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 12 }}
        run: npm run lint

      - name: Run tests
        run: npm run testonly:cov -- --colors

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 12 }}
        with:
          fail_ci_if_error: true
